#!/usr/bin/env bash


if [[ -z $1 ]]; then
  echo "Please provide file name as a first argument!"
  exit 1
fi

if [[ -z $2 ]]; then
  echo "Please provide variable name as a second argument!"
  exit 2
fi


COMMIT_ID=`git rev-parse HEAD`

sed -i '' "s/^\($2\)=.*/\1=$COMMIT_ID/" $1
